### PR TITLE
Added migrations.

### PR DESCRIPTION
**Pull request by alekosot**
Added migrations needed for compatibility with django's `manage.py migrate` command.

### CODE REVIEW

**Comment by dfunckt** [comment]
Does it work if, instead of using `emailauth.User` as-is, a user extends it and sets `AUTH_USER_MODEL = 'myapp.models.CustomUser'`?

Thanks for the PR :)

**Comment by alekosot** [comment]
Yes, it works normally. Someone still needs to run `makemigrations` for the subclass's migration files to be created however.

I tested with a subclass and a relation to it, as per the [docs](https://docs.djangoproject.com/en/1.10/topics/auth/customizing/#referencing-the-user-model) (i.e `ForeiqnKey(settings.AUTH_USER_MODEL)`). No problems encountered.

**Edit**
It seems that I had some extra migrations in the project I tested this on. Let me get back to you on this one, since subclasses do not work as expected after all :(

**Comment by dfunckt** [comment]
While you're at it can you please check that inheriting from `AbstractBaseUser` instead works? I think subclassing `User` is not supposed to work as per the green note here: https://docs.djangoproject.com/en/1.10/topics/auth/customizing/#substituting-a-custom-user-model

I believe you'll have to omit `emailauth` from `INSTALLED_APPS` in this case though, and use it as a simple library.

**Comment by dfunckt** [comment]
I mean extend from `emailauth.models.AbstractUser`, not `AbstractBaseUser`.

**Comment by alekosot** [comment]
Subclassing from `emailauth.models.AbstractUser` works normally and seems indeed the appropriate way to go if you want to customize `emailaith.models.User`.

Otherwise, if a subclass of `emailauth.models.User` is set as `AUTH_USER_MODEL`, then two different issues arise:
-  If `emailauth` is in `INSTALLED_APPS`, then django complains that there is a relation to a model that has been swapped out.
-  If `emailauth` is not in `INSTALLED_APPS`, then django complains that it cannot find the app `emailauth`, which can be solved with `app_label = 'email_auth'` in `User`'s `class Meta`, but then there is the problem with the relation to a non existing model.

So, everything works as expected and I don't think I am missing anything this time... :)

**Comment by dfunckt** [comment]
Yep, it looks perfect, thanks a lot for your tests! Merging.

**Pull request merged**
